import fs from 'node:fs'
import { getAllImageFiles } from '@/libs/blog'

const files = getAllImageFiles()
const stream = fs.createWriteStream('src/libs/images/manifest.ts')

stream.write(`// This file is generated by scripts/image-manifest.ts\n`)
stream.write(`import { StaticImageData } from 'next/image'\n`)
stream.write(`const images: { [k: string]: StaticImageData } = {}\n`)

for (const file of files) {
  stream.write(`images['${file.urlPath}'] = require('@${file.filePath}')\n`)
}

stream.write(`export default images\n`)
